"""empty message

Revision ID: 1086a5a24252
Revises: 77c383247090
Create Date: 2018-02-24 14:42:51.905509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1086a5a24252'
down_revision = '77c383247090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_layer_layer_id'), 'tag_layer', ['layer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_layer_layer_id'), table_name='tag_layer')
    op.drop_table('tag_layer')
    # ### end Alembic commands ###
