"""empty message

Revision ID: 42bd77b70eb3
Revises: 90dc4e8d543e
Create Date: 2018-04-04 10:45:00.615669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bd77b70eb3'
down_revision = '90dc4e8d543e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('official', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'official')
    # ### end Alembic commands ###
