"""empty message

Revision ID: 724156669506
Revises: d386cddcf87f
Create Date: 2018-02-24 17:13:12.241531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724156669506'
down_revision = 'd386cddcf87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'tag_layer_layer_id_tag_id_key', 'tag_layer', type_='unique')
    op.drop_index('tag_layer_tag_id_layer_id_idx', table_name='tag_layer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tag_layer_tag_id_layer_id_idx', 'tag_layer', ['tag_id', 'layer_id'], unique=False)
    op.create_unique_constraint(u'tag_layer_layer_id_tag_id_key', 'tag_layer', ['layer_id', 'tag_id'])
    # ### end Alembic commands ###
