"""empty message

Revision ID: 760e1b768dbf
Revises: c3832ddad82e
Create Date: 2018-05-18 22:34:11.805489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760e1b768dbf'
down_revision = 'c3832ddad82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('analysed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'analysed')
    # ### end Alembic commands ###
