"""empty message

Revision ID: 77c383247090
Revises: f0c0c430f0ba
Create Date: 2018-02-21 20:39:18.209842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c383247090'
down_revision = 'f0c0c430f0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('affiliation', sa.String(length=255), nullable=True))
    op.add_column('image', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('image', sa.Column('is_automated', sa.Boolean(), nullable=True))
    op.add_column('image', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('image', sa.Column('pull_count', sa.BigInteger(), nullable=True))
    op.add_column('image', sa.Column('repository_type', sa.String(length=255), nullable=True))
    op.add_column('image', sa.Column('star_count', sa.BigInteger(), nullable=True))
    op.add_column('image', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'status')
    op.drop_column('image', 'star_count')
    op.drop_column('image', 'repository_type')
    op.drop_column('image', 'pull_count')
    op.drop_column('image', 'last_updated')
    op.drop_column('image', 'is_automated')
    op.drop_column('image', 'description')
    op.drop_column('image', 'affiliation')
    # ### end Alembic commands ###
