"""empty message

Revision ID: 90dc4e8d543e
Revises: 2722f0aa619f
Create Date: 2018-03-31 18:18:52.027135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dc4e8d543e'
down_revision = '2722f0aa619f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('last_try', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'last_try')
    # ### end Alembic commands ###
