"""empty message

Revision ID: 9e252694543f
Revises: 
Create Date: 2018-02-15 16:22:58.477919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e252694543f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_featureversion_feature_id'), 'featureversion', ['feature_id'], unique=False)
    op.drop_index('featureversion_feature_id_version_key', table_name='featureversion')
    op.create_index('featureversion_feature_id_version_key', 'featureversion', ['feature_id', 'version'], unique=False)
    op.drop_index('featureversion_feature_id_idx', table_name='featureversion')
    op.create_index(op.f('ix_layer_namespace_id'), 'layer', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_layer_parent_id'), 'layer', ['parent_id'], unique=False)
    op.drop_index('layer_namespace_id_idx', table_name='layer')
    op.drop_index('layer_parent_id_idx', table_name='layer')
    op.create_index(op.f('ix_layer_diff_featureversion_featureversion_id'), 'layer_diff_featureversion', ['featureversion_id'], unique=False)
    op.create_index(op.f('ix_layer_diff_featureversion_layer_id'), 'layer_diff_featureversion', ['layer_id'], unique=False)
    op.drop_index('layer_diff_featureversion_featureversion_id_idx', table_name='layer_diff_featureversion')
    op.drop_index('layer_diff_featureversion_layer_id_idx', table_name='layer_diff_featureversion')
    op.create_index(op.f('ix_lock_owner'), 'lock', ['owner'], unique=False)
    op.drop_index('lock_owner_idx', table_name='lock')
    op.drop_index('namespace_name_key', table_name='namespace')
    op.create_unique_constraint(None, 'namespace', ['name'])
    op.create_index(op.f('ix_vulnerability_name'), 'vulnerability', ['name'], unique=False)
    op.drop_index('vulnerability_name_idx', table_name='vulnerability')
    op.create_index(op.f('ix_vulnerability_affects_featureversion_fixedin_id'), 'vulnerability_affects_featureversion', ['fixedin_id'], unique=False)
    op.drop_index('vulnerability_affects_featureversion_fixedin_id_idx', table_name='vulnerability_affects_featureversion')
    op.create_index(op.f('ix_vulnerability_notification_deleted_at'), 'vulnerability_notification', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vulnerability_notification_notified_at'), 'vulnerability_notification', ['notified_at'], unique=False)
    op.drop_index('vulnerability_notification_deleted_at_idx', table_name='vulnerability_notification')
    op.drop_index('vulnerability_notification_notified_at_idx', table_name='vulnerability_notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('vulnerability_notification_notified_at_idx', 'vulnerability_notification', ['notified_at'], unique=False)
    op.create_index('vulnerability_notification_deleted_at_idx', 'vulnerability_notification', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_vulnerability_notification_notified_at'), table_name='vulnerability_notification')
    op.drop_index(op.f('ix_vulnerability_notification_deleted_at'), table_name='vulnerability_notification')
    op.create_index('vulnerability_affects_featureversion_fixedin_id_idx', 'vulnerability_affects_featureversion', ['fixedin_id'], unique=False)
    op.drop_index(op.f('ix_vulnerability_affects_featureversion_fixedin_id'), table_name='vulnerability_affects_featureversion')
    op.create_index('vulnerability_name_idx', 'vulnerability', ['name'], unique=False)
    op.drop_index(op.f('ix_vulnerability_name'), table_name='vulnerability')
    op.drop_constraint(None, 'namespace', type_='unique')
    op.create_index('namespace_name_key', 'namespace', ['name'], unique=True)
    op.create_index('lock_owner_idx', 'lock', ['owner'], unique=False)
    op.drop_index(op.f('ix_lock_owner'), table_name='lock')
    op.create_index('layer_diff_featureversion_layer_id_idx', 'layer_diff_featureversion', ['layer_id'], unique=False)
    op.create_index('layer_diff_featureversion_featureversion_id_idx', 'layer_diff_featureversion', ['featureversion_id'], unique=False)
    op.drop_index(op.f('ix_layer_diff_featureversion_layer_id'), table_name='layer_diff_featureversion')
    op.drop_index(op.f('ix_layer_diff_featureversion_featureversion_id'), table_name='layer_diff_featureversion')
    op.create_index('layer_parent_id_idx', 'layer', ['parent_id'], unique=False)
    op.create_index('layer_namespace_id_idx', 'layer', ['namespace_id'], unique=False)
    op.drop_index(op.f('ix_layer_parent_id'), table_name='layer')
    op.drop_index(op.f('ix_layer_namespace_id'), table_name='layer')
    op.create_index('featureversion_feature_id_idx', 'featureversion', ['feature_id'], unique=False)
    op.drop_index('featureversion_feature_id_version_key', table_name='featureversion')
    op.create_index('featureversion_feature_id_version_key', 'featureversion', ['feature_id', 'version'], unique=True)
    op.drop_index(op.f('ix_featureversion_feature_id'), table_name='featureversion')
    # ### end Alembic commands ###
