"""empty message

Revision ID: b5804cc3263d
Revises: 724156669506
Create Date: 2018-02-27 18:07:53.714759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5804cc3263d'
down_revision = '724156669506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('manifest', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'manifest')
    # ### end Alembic commands ###
