"""empty message

Revision ID: b744c18d06b8
Revises: f0c412267bb3
Create Date: 2018-03-12 10:13:38.286869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b744c18d06b8'
down_revision = 'f0c412267bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('manifest_v1', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'manifest_v1')
    # ### end Alembic commands ###
