"""empty message

Revision ID: c3832ddad82e
Revises: 8fcba8c805b5
Create Date: 2018-05-18 20:40:33.137276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3832ddad82e'
down_revision = '8fcba8c805b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'score')
    # ### end Alembic commands ###
