"""empty message

Revision ID: ca0995fe7554
Revises: a5f6e5ef172e
Create Date: 2018-04-13 09:57:55.932303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0995fe7554'
down_revision = 'a5f6e5ef172e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('packages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'packages')
    # ### end Alembic commands ###
