"""empty message

Revision ID: d386cddcf87f
Revises: 54bc69c4f532
Create Date: 2018-02-24 16:43:36.861626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd386cddcf87f'
down_revision = '54bc69c4f532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'tag_layer_layer_id_fkey', 'tag_layer', type_='foreignkey')
    op.drop_constraint(u'tag_layer_tag_id_fkey', 'tag_layer', type_='foreignkey')
    op.create_foreign_key(None, 'tag_layer', 'tag', ['tag_id'], ['id'], ondelete=u'CASCADE')
    op.create_foreign_key(None, 'tag_layer', 'layer', ['layer_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_layer', type_='foreignkey')
    op.drop_constraint(None, 'tag_layer', type_='foreignkey')
    op.create_foreign_key(u'tag_layer_tag_id_fkey', 'tag_layer', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(u'tag_layer_layer_id_fkey', 'tag_layer', 'layer', ['layer_id'], ['id'])
    # ### end Alembic commands ###
