"""empty message

Revision ID: f0c0c430f0ba
Revises: 3f91a3acedb0
Create Date: 2018-02-20 15:36:48.717494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c0c430f0ba'
down_revision = '3f91a3acedb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'image_full_name_key', 'image', type_='unique')
    op.add_column('tag', sa.Column('last_check', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(u'tag_image_id_name_key', 'tag', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'tag_image_id_name_key', 'tag', ['image_id', 'name'])
    op.drop_column('tag', 'last_check')
    op.create_unique_constraint(u'image_full_name_key', 'image', ['full_name'])
    # ### end Alembic commands ###
