"""empty message

Revision ID: f0c412267bb3
Revises: b5804cc3263d
Create Date: 2018-03-09 14:46:17.085595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c412267bb3'
down_revision = 'b5804cc3263d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('tags_checked', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'tags_checked')
    # ### end Alembic commands ###
